services:
  - type: web
    name: calgarycommunity-django
    env: python
    plan: free
    runtime: python
    buildCommand: >
      pip install --upgrade pip &&
      pip install wheel &&
      pip install -r requirements.txt
    startCommand: "gunicorn calCrimes.wsgi"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: calCrimes.settings
      - key: DB_NAME
        fromDatabase:
          name: calgarycommunity_fcgj
          property: database
      - key: DB_USER
        fromDatabase:
          name: calgarycommunity_fcgj
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: calgarycommunity_fcgj
          property: password
      - key: DB_HOST
        fromDatabase:
          name: calgarycommunity_fcgj
          property: host
      - key: DB_PORT
        fromDatabase:
          name: calgarycommunity_fcgj
          property: port