services:
  - type: web
    name: calgarycommunity-django
    env: docker
    dockerImage: beckdocker/calgarycommunity
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Urking1!@db.flsgrbtpuhbgdpsokfss.supabase.co:5432/postgres