services:
  - type: web
    name: calgarycommunity-django
    env: docker
    image: beckdocker/calgarycommunity
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:yourpassword@db.flsgrbtpuhbgdpsokfss.supabase.co:5432/postgres