# Generated by Django 5.0.7 on 2024-08-02 15:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=50)),
                ("comm_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sector", models.CharField(max_length=255)),
                ("srg", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "comm_structure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_dt", models.DateTimeField()),
                ("modified_dt", models.DateTimeField()),
                (
                    "multipolygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrimesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("january", models.IntegerField(blank=True, default=0, null=True)),
                ("february", models.IntegerField(blank=True, null=True)),
                ("march", models.IntegerField(blank=True, null=True)),
                ("april", models.IntegerField(blank=True, null=True)),
                ("may", models.IntegerField(blank=True, null=True)),
                ("june", models.IntegerField(blank=True, null=True)),
                ("july", models.IntegerField(blank=True, null=True)),
                ("august", models.IntegerField(blank=True, null=True)),
                ("september", models.IntegerField(blank=True, null=True)),
                ("october", models.IntegerField(blank=True, null=True)),
                ("november", models.IntegerField(blank=True, null=True)),
                ("december", models.IntegerField(blank=True, null=True)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.community",
                    ),
                ),
            ],
        ),
    ]
