# Generated by Django 5.0.7 on 2024-08-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="class_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
