# Generated by Django 5.0.7 on 2024-08-07 16:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_community_class_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Community Centre", "Community Centre"),
                            ("Attraction", "Attraction"),
                            ("Library", "Library"),
                            ("Court", "Court"),
                            ("Hospital", "Hospital"),
                            ("PHS Clinic", "PHS Clinic"),
                            ("Commercial", "Commercial"),
                            ("Visitor Info", "Visitor Info"),
                            ("Social Dev Ctr", "Social Dev Ctr"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("comm_code", models.CharField(max_length=10)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
