# Generated by Django 5.0.7 on 2024-08-07 16:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward", models.CharField(max_length=255)),
                ("total_household_total_income", models.IntegerField()),
                ("under_20_000", models.IntegerField()),
                ("_20_000_to_39_999", models.IntegerField()),
                ("_40_000_to_59_999", models.IntegerField()),
                ("_60_000_to_79_999", models.IntegerField()),
                ("_80_000_to_99_999", models.IntegerField()),
                ("_100_000_to_124_999", models.IntegerField()),
                ("_125_000_to_149_999", models.IntegerField()),
                ("_150_000_to_199_999", models.IntegerField()),
                ("_200_000_and_over", models.IntegerField()),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
