# Generated by Django 5.0.7 on 2024-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="income",
            field=models.IntegerField(default=0),
        ),
    ]
