# Generated by Django 5.0.7 on 2025-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_community_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedDataCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("data", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
