"""
Django settings for calCrimes project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import dj_database_url
from pathlib import Path
import environ
import os

# Initialize environment variables
env = environ.Env()
# 根據 DJANGO_ENV 判斷要載入哪個 .env
ENV_FILE = ".env.prod" if os.getenv("DJANGO_ENV") == "production" else ".env.dev"
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, ENV_FILE))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
env.read_env(os.path.join(BASE_DIR, ".env"))


SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key")

DEBUG = os.getenv("DEBUG", "False") == "True"


ALLOWED_HOSTS = [os.getenv("RENDER_EXTERNAL_HOSTNAME", "localhost")]

import os, platform

system = platform.system()

if system == "Windows":
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", r"C:\OSGeo4W\bin\gdal310.dll")
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH", r"C:\OSGeo4W\bin\geos_c.dll")

elif system == "Darwin":  # macOS
    GDAL_LIBRARY_PATH = os.getenv(
        "GDAL_LIBRARY_PATH", "/opt/homebrew/Cellar/gdal/3.10.2/lib/libgdal.dylib"
    )
    GEOS_LIBRARY_PATH = os.getenv(
        "GEOS_LIBRARY_PATH", "/opt/homebrew/Cellar/geos/3.12.2/lib/libgeos_c.dylib"
    )

elif system == "Linux":
    # ⚠️ Render 通常不需要設定 GDAL_LIBRARY_PATH / GEOS_LIBRARY_PATH
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", "/usr/lib/libgdal.so")
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH", "/usr/lib/libgeos_c.so")

else:
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH")
    GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH")

    if not GDAL_LIBRARY_PATH or not GEOS_LIBRARY_PATH:
        raise RuntimeError("Unsupported OS or missing GDAL/GEOS library paths")


# if os.getenv("DJANGO_ENV") == "development":
#     GDAL_LIBRARY_PATH = "C:\\OSGeo4W\\bin\\gdal310.dll"  # Windows
#     GEOS_LIBRARY_PATH = "C:\\OSGeo4W\\bin\\geos_c.dll"  # Default for Windows

# if platform.system() == "Darwin":  # macOS
#     GDAL_LIBRARY_PATH = os.getenv(
#         "GDAL_LIBRARY_PATH", "/opt/homebrew/Cellar/gdal/3.10.2/lib/libgdal.dylib"
#     )
#     GEOS_LIBRARY_PATH = os.getenv(
#         "GEOS_LIBRARY_PATH", "/opt/homebrew/Cellar/geos/3.12.2/lib/libgeos_c.dylib"
#     )
# elif platform.system() == "Linux":
#     GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", "/usr/lib/libgdal.so")
#     GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH", "/usr/lib/libgeos_c.so")
# else:
#     GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH")
#     GEOS_LIBRARY_PATH = os.getenv("GEOS_LIBRARY_PATH")
#     if not GDAL_LIBRARY_PATH or not GEOS_LIBRARY_PATH:
#         raise RuntimeError("Unsupported OS or missing GDAL/GEOS library paths")

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    # 3rd part apps
    "django_cleanup.apps.CleanupConfig",
    "rest_framework",
    "rest_framework_gis",
    "clearcache",
    # Local apps
    "backend.apps.BackendConfig",  # in apps.py
    # "frontend.apps.FrontendConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "calCrimes.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "calCrimes.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.contrib.gis.db.backends.postgis"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

STATIC_URL = "/static/"
if os.getenv("DJANGO_ENV") == "development":
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]
else:
    ## python manage.py collectstatic
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
